//Make an Object
let horoscope = {
    Nile: "Your avatar is Hapi, one so closely connected with the flooding of the nile and the fertility that it brought to the land that it was also referred to as 'Nile' in ancient Kemet. The reason why you are considered Hapi is because you operate from a place of abundance even when life's hardships cloud you with harsh circumstances and bad weather. You are able to direct your focus into an orderly harmonious system that can benefit both you and the collective as well as can generate prospertity. Flow state is important to you and it is equally important for you to remain connected with wise council who may provide resources that keep you effectively making sound decisions.",
    AmunRa: "Widely considered as King of the Gods, Ra is a sun sign similiar to Leo in Western Astrology. Conversely, 'Amun' was considered the hidden one and represented the pervasive omnipotence of the most high. As an avatar Amun Ra represents the confident, optimistic, and leadership qualities inherent in your nature. You will not be satisfied with mediocrity or 'averageness'. You intend to leave a mark on the world thorugh your devoted acts and have the willpower to see your ambitions through to fruition. You have strong faith and believe in yourself.",
    Mut: "Pronounced 'Moot' Mut is the divine feminen principle of Motherhood and represents the patience, rationality and wisdom that you express among your friends and loved ones. Mut was said to be a primodeal Goddess who helped form the world through A-sexual reproduction. Also, associated with the primodial waters of 'Nu' which is the lifeblood or the aqueous core of everything in existence. She is also heavily connected with the energy of Amun-Ra who is considered, the king of their pantheon and her husband. With Mut as your avatar, Family and Education may be a priority for you. You can thrive in circumstances relating to helping youth evolve or learning no matter the age. In addition, you are committed to bettering yourself and aiding your expansion. At first, you may be somewhat standoffish and shy until you get to know people but once you're a friend you are a friend for life.",
    Geb:"Geb represents connection between Earth and water. Therefore he is relatable, emotionally intelligent, empathetic and has a good sense of humor. He is said to cause earthquakes by laughing and his down to earth nature is partially why he presides over snakes. Other animals that represent him are ducks/geese, mongoose and Lizards. Ancient Kemet is one of the few cultures who ever represented the Earth as a male diety and as such he is deeply involved with Nut (pronounced 'noot'), the Sky Goddess. His values revolve around matters that take place on land, for instance: community, diplomacy, reliability, and intelligence. Often it is said that his bones are made from rock formations like mountains and that he is constantly making love to the heavens. People with Geb as an avatar are solid, monogamous and intellectual but they may become unsettled when the time comes to set clear boundaries. Parallels to the Western Astrological sign of Aquarius may make sense for people with this avatar.", 
    Asar:"Asar is known as the Neter (Nature) of Renewal. In his story, he was the hieght of his power when his brother decieved him with a gift and trapped him in a box (representative of transitioning from a God-like diety to experience mortality for the first time.) People born with Asar as their avatar are dual natured. They can both be a symbol of strong leadership, determination and willpower while still maintaining a level of gullibility and indecision that leaves them vulnerable. Their issues may threaten to delay/re-route the fulfillment of their goals and aspirations. They are often charismatic, intellectual, and blunt in communications. They don't enjoy following orders, are often entreprenuerial and sometimes may appear selfish in their candor. Despite the fact that they have big hearts and are very optimistic people at their core. Ancient Kemetic belief was the afterlife runs parallel to life as we know it & that souls exist indefinitely there once they transtion. It is also a popular belief, that the world visited when dreaming is the same as the world of the afterlife and that it prepared you for your transition once the person passed away. In principle, Ausar is the guardian of that veil and helps to ensure safe passage between states of conciousness. In the world at large, his story of rebirth is reminiscent to that of religious figures and myths like Persephone. For those living in more temparate climates, imagine his essence being similiar to the transition of winter to spring.",
    Auset:"Auset is a natural healer and epitomizes wisdom. She is the archetype for every venerated mother across history and was dubbed by the Roman's as the 'Goddess of Ten Thousand Names'. Her grace and regal stature makes her an asset to royal succession, so much so that there may be NO kingdom without you or another representative of her avatar present. She is the patroness of children, the poor, the wounded. People who embody her characteristics eminate an elegance and grace while skillfully excercising hard to do tasks. You are most likely straightforward, open and have a charming sense of humor. You work as well on a team as you do alone and are able to help fuse together a broken heart as you step into your own wholeness. You are capable of deep forgiveness but once crossed have an inate sense of never retreading old treacherous water. You have the gift of clarity and an unmatched sense of how to transform trauma into tools and techniques to avoid it in the future. You have a respect for the inner magic in all things and move with honor/integrity. Auset is one of the only dieties who was able to decipher the secrets of the universe and learn the most high's true name. You are someone who deserves veneration and protection, at all costs. Therefore you may be seen as demanding, obliged and someone who plays the role of martyr. You're closest sign in Western zodiac is a Pisces.",
    Djehuti:"Djehuti Mas or Thoth is also known as Hermes thrice Great or Enoch from The Bible. He is the keeper of the akashic records as well as its author. Well known as the archetype for writers and the erudite students with a lifelong passion for learning. He brings these people dignity and assists in tests of skill. People with Djehuti Mas as an avatar are pioneers of the arts and sciences. You are most likely an inventor, teacher, accountant or lawyer considering that Djehuti is well known for being persistent and devoted to the need to uphold the truth. You may be considered an authority over your skillset and if you are out of balance it will be starkly pronounced and hard to accept by the public. Considering that Djehuti is the gaurdian of justice in Ma'at if you violate the law or any personal code of ethics that you live by you will pose a signicant threat to your reputation, so tread carefully. Remember Djehuti invented the hieroglypic script and negotiated five extra days from the moon so that there would be a 365 day annual cycle, so your proficiency with coding and/or negotiations will be bar none. You most likely have great communication skills and may be highly opinionated. Your high standards when it comes to service and honesty may repel people since it makes you seem like a goody two shoes. It may also become hard to get through to you due to a stubborn know it all persona that prevents you from being receptive to new ideas. This perspective may also bring unwarranted difficulty in navigating social environments because people may betray you or hide things from you out of fear of being judged. Conversely, people judge you and your truth harshly quite often and will go through great expense to blackball you out of fear of the threat you pose. Consider Toth's involvement in writing the Emerald Scrolls, The omission of The Book of Encoh from most modern versions of The Bible and people's general disregard of concepts like The Akashic Records as psuedo-science as proof of your ability to ruffle feathers and challenge the status quo. Overall, your great wealth of knowledge may remain an underground phenomena that people have no idea of because your relentless pursuit of truth flew you too close to the sun. Your closest western astrological sign is a Libra.",
    Heru:"The paragon of heroism and quintessential figure in the heros journey, Heru is the son of Auset and Ausar and is represented by the falcon. Keen awareness, high level vision and an unyielding devotion to the fight for justice Heru is a symbol of strength and resilience. His life was about restoring the balance of goodness and truth over negative forces. People who embody his avatar are quick-witted, alert and have the staying power of just leadership. Detail oriented, it's hard to get one by you!! You have an inate ability to provide great counsel and often find yourself ascending to the highest positions in an organization and staying there for quite some time for the value you are able to provide. Typically these people have political ambitions and aim to serve the public with their station. They serve their loved ones and supporters very well however the people who disagree with their stance can feel bullied and pressured by the candor and willpower of these people. Overall, they are inspiring albeit somewhat stubborn and forceful.", 
    Anpu:"Also known as Anubis, people with this avatar are usually more reserved, duty oriented and prefer the company of a close-knit circle to shallow interactions. Anpu is full of valuable insight as it pertains to discernment and decision making. He is always carefully evaluating circumstances and people without being swayed by the superficial. This ability proves quite useful in professional environments and their principled morality also helps with longevity in religious practice/ceremony. Anpu's role in ancient kemetic thought was to guide souls in the afterlife and to preserve the most crucial elements of them through the mumification process. Although this may seem macabre, there is a level of maturity and comfortability with the balance of life and death for people who embody this avatar's characteristics. Their ability to get to the root of circumstances and play mediator is invaluable in arguments as they are known to be level-headed and fair. Although their season is not in the fall, their closest western astrological counterpart is Scorpio.", 
    Set:"Set is the principle that fixes things in place and gives this world's elements weight, mass and a finite end. The name 'Set' loosely translates into 'dazzling' and in the oldest mythologies Set is known as the 'He Before whom the Sky Shakes,'. Set is the demonized diety whose legacy is that of a deciever. He tricked his brother Ausar into being trapped and dismembered in order to stage a coup over his kingdom. Due to his transgression and the reign to follow he is known as the preeminent diety of chaos, strength and transformation. People with set as an avatar may harbor evil thoughts and/or they may need to learn how to be resilient and adaptable when navigating obstacles because they don't have the same scruples others may have in regards to honor. They will not be a stranger to struggle and opposition considering that people who don't believe in them feel vindicated in their opposing view. A major strength of these people is the ability to embrace chaotic circumstances as a tool for growth and renewal. In fact, Set is an agent of extreme duality. Having originally been considered the God of the desert and overtime taking on the role of God of Storms and Warfare. The mind of a Set-ian avatar is always running a cycle of creation and destruction. He was the protector of the Sun God Ra in its journey through the underworld so it can reflect the charm of a good humor in the darkest moments. Ultimately, Set deals with opposition from the most powerful dieties in this pantheon having fought against Ausar, Auset, and Horus (where he ultimately meets his demise). As a Setian personality type you may be a perfectionist and have a indestructible determination no matter who tries to stand in your way! You may be captivatingly different and stand out in the crowd. However you appreciate the attention and are sociable as well as thrive when attention is lavished upon you. The disorder and malevolence of your Setian avatar are very pronounced and hard to escape however so it will remain important for you to be mindful of the golden rule and to treat other how you'd like to be treated.",
    Bastet:"Bastet is an avatar of music, pleasure and domestic protection. She was once seen as a fierce lion similiar to Sekhmet sent to Earth by Ra as a divine punishment for humanity but once she arrived she was decieved into a drunken state and her fun-loving & kind nature was revealed. Although percotious and powerful, People with Bastet energy dont seek conflict nor do they thrive in hostile environments. Instead they command a regal heir about them and endulge in tasks of a more creative nature. Endowed with keen intuition and connected to the unseen realms people who are born during this time may be mysterious with an inexplicable inner-knowing. They are well guided through the obstacles in life and have a cat-like dexterity about them. Not only are these people creative but they are fiercely protective over that which they create and love and often will go up against exploitive and suspicious characters who wont see the value in what they've made. They fight equally passionately for children and pregnant mothers and for that reason are protectors and defenders of their families and the home as a unit. Usually, they are bestowed lavish gifts and benefit from social gatherings. They can be the life of the party and for that reason they may need to excercise restraint for these people are not at all immune to the spoils of excess. Despite at times being possessive You make strong connections with others and are loyal, devoted, affectionate and even on more than one occasion sensetive to the ways of others. Beware of people pleasing and putting your needs off to the side for others. Since you value peace and are also a strong defender you may be the one that seeks common ground, verbal mediation or a more evasive alternative to irreparable violence. Ultimately you are very considerate of those around you and will only get rowdy as a last resort. You are the salt of the earth and have a way of making the world just a tadbit better just by being around. You must remember not to get too introverted, depressed or low about yourself because the woe wont last and the world would be honored to dance at your feet.",
    Sekhmet: "Sekhmet is a fierce warrior who can be unrelenting as a force of retribution for the most high, Ra in Kemetic cosmology. She is a lioness and hunter so patrons with this avatar may be perfectionists and strict. They adhere tightly to their values and dispise hipocracy although they themselves are somewhat dual in nature as well. Sekhmet can be fun and charismatic with a great sense of humor but conversely it stems from their more serious side. They are great judges of character, very admirable in their execution of tasks and often view obstacles as learning opportunities. You are a resilient and formidable healer who harnesses the potential for much growth and inner transformation. In fact, if you have gone into medicine you are divinely paired with Sekhmet because she set the standard for surgery and comprehensive care in the ancient world. Conversely, as the embodiment of Ra's righteous vengence you may apply that carnal knowledge to being a deadly force that amoral people ought be weary of. Your keen discernment makes the strongest attribute you have that of appropriate action. You usually know just what to do, how to do it effectively and who to do it to. Just try to stay graceful when you cannot be sweet or gentle, there is an heir of feral virility to you that can cause apprehension and anxe among people you may even enjoy being around. It does'nt hurt to take a bubblebath when noone is looking or to pamper yourself in a way only you know!", 
    Maat: "Ma'at is the paragon of order, justice and righteous action. She is the avatar for judges, magistrates and court officials and quite often sets the standard for how things are meant to be done. You either are a grandparent or have a strong connection to the elderly because being wise is second nature to you. Maybe you were a first born sibling. You are endowed with sound mind, strong logic and reasoning. People around you may consider you incorruptible or such a good role model that they compare themselves to you incessantly. Beware of those people who dont see your flaws because they may not be able to empathise when something bad happens. You may even benefit from consulting a therapist so that your emotional needs dont get swept under the wayside when dealing with others. It is often the strong friend that never gets checked on!", 
} 

//Make A function to determine Zodaic Sign based on birthday
function zodiacDetermined(month, day){
    //The following are logical operators for conditional statements that say, the month is equal to a certain number then  an operand that says the range for that day and the end of the cycle which is represented by a less than or equal to symbol.  
    if ((month === 1 && day >= 1) && (month === 1 && day <= 7))return "Nile"; 
    if ((month === 6 && day >= 19) && (month === 6 && day <= 28))return "Nile";
    if ((month === 9 && day >= 1) && (month === 9 && day <= 7))return "Nile";
    if ((month === 11 && day >= 18) && (month === 11 && day <= 26))return "Nile";
    if ((month === 1 && day >= 8) && (month === 1 && day <= 21)) return "AmunRa";
    if ((month === 2 && day >= 1) && (month === 2 && day <= 11)) return "AmunRa";
    if ((month === 1 && day >= 22) && (month === 1 && day <= 31)) return "Mut";
    if ((month === 9 && day >= 8) && (month === 9 && day <= 22)) return "Mut";
    if ((month === 2 && day >= 12) && (month === 2 && day <= 29)) return "Geb";
    if ((month === 8 && day >= 20) && (month === 8 && day <= 31)) return "Geb";
    if ((month === 3 && day >= 1) && (month === 3 && day <= 10)) return "Asar";
    if ((month === 11 && day >= 27) || (month === 12 && day <= 18)) return "Asar";
    if ((month === 10 && day >= 18) && (month === 10 && day <= 29)) return "Auset";
    if ((month === 12 && day >= 19) && (month === 12 && day <= 31)) return "Auset";
    if ((month === 4 && day >= 1) && (month === 4 && day <= 19)) return "Djehuti";
    if ((month === 11 && day >= 8) && (month === 11 && day <= 17)) return "Djehuti";
    if ((month === 8 && day >= 12) && (month === 8 && day <= 19)) return "Heru";
    if ((month === 4 && day >= 20) || (month === 5 && day <= 7)) return "Heru"; 
    if ((month === 6 && day >= 29) || (month === 7 && day <= 13)) return "Anpu";
    if ((month === 5 && day >= 8) && (month === 5 && day <= 27)) return "Set";
    if ((month === 9 && day >= 28) || (month === 10 && day <= 2)) return "Maat";
    if ((month === 3 && day >= 10) && (month === 3 && day <= 31)) return "Maat";
    if ((month === 5 && day >= 28) || (month === 6 && day <= 18)) return "Bastet";
    if ((month === 6 && day >= 19) || (month === 7 && day <= 28)) return "Bastet";
    if ((month === 9 && day >= 23) && (month === 9 && day <= 27)) return "Bastet";
    if ((month === 10 && day >= 3) && (month === 10 && day <= 17)) return "Bastet";
    if ((month === 7 && day >= 29) || (month === 8 && day <= 11)) return "Sekhmet";
    if ((month === 10 && day >= 30) || (month === 11 && day <= 7)) return "Sekhmet";
return ("invalid, there is no match.")
}


    //Function to get horoscope
    const eventListener=document.querySelector("button").addEventListener("click", () => {
    const date=document.querySelector("input").value.split("-")
    const egyptianGod= zodiacDetermined (Number(date[1]), Number(date[2]))
    // alert(date)
    // alert(egyptianGod)    
    // alert(horoscope[egyptianGod])
    document.getElementById("result").innerHTML=`
        <h1>${egyptianGod}</h1>
        <img src="img/${egyptianGod}.jpg">
        <p>${horoscope[egyptianGod]}</p>`
    });